//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupLessonTimes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupLessonTimes()
        {
            this.GroupTypes = new HashSet<GroupTypes>();
        }
    
        public int GroupLessonTimeId { get; set; }
        public string GroupLessonTimeName { get; set; }
        public System.TimeSpan GroupLessonTimeStart { get; set; }
        public System.TimeSpan GroupLessonTimeEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTypes> GroupTypes { get; set; }
    }
}
