//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Groups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Groups()
        {
            this.Students = new HashSet<Students>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public int ProgramId { get; set; }
        public int TeacherId { get; set; }
        public int MentorId { get; set; }
        public int GroupTypeId { get; set; }
        public Nullable<System.DateTime> GroupStartDate { get; set; }
        public Nullable<System.DateTime> GroupEndDate { get; set; }
    
        public virtual EducationPackages EducationPackages { get; set; }
        public virtual GroupTypes GroupTypes { get; set; }
        public virtual Mentors Mentors { get; set; }
        public virtual Teachers Teachers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students> Students { get; set; }
    }
}
