//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int MessageId { get; set; }
        public string MessageSubject { get; set; }
        public string MessageContent { get; set; }
        public System.DateTime MessageSendTime { get; set; }
    }
}
