//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducationProject.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.StudentTasks = new HashSet<StudentTasks>();
        }
    
        public int StudentId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public int UserId { get; set; }
        public string StudentName { get; set; }
        public string StudentSurname { get; set; }
        public string StudentEmail { get; set; }
        public Nullable<System.DateTime> StudentBirthDate { get; set; }
        public string StudentPhone { get; set; }
        public System.DateTime StudentRegistrationDate { get; set; }
        public string StudentPhoto { get; set; }
        public string StudentBio { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTasks> StudentTasks { get; set; }
    }
}
